version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=bilgihan_chatbot.py
      - FLASK_ENV=development
    env_file:
      - .env
